source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.11'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'spree_shipstation', github: 'DynamoMTL/spree_shipstation', branch: '2-4-stable'
gem 'spree_active_shipping', github: 'spree-contrib/spree_active_shipping', branch: '2-4-stable'
# gem 'spree_elasticsearch', github: 'javereec/spree_elasticsearch', branch: '2-4-stable'
# gem 'searchkick'

group :development do

  # Use Capistrano for deployment
  gem 'capistrano-rails'
  gem 'capistrano-passenger'
  gem 'capistrano-bundler'
  gem 'capistrano-rvm'
  
  # Notification to ammolist.slack.com about deployment
  gem 'capistrano-slackify'
  gem 'better_errors'
  gem 'mailcatcher'

end


gem 'redmine-reporting'
gem 'newrelic_rpm'
gem 'aws-sdk'
gem 'gaffe'

# Responsive jQuery lightbox plugin, for image pop-up
gem 'magnific-popup-rails', '~> 0.9.9.1'

# Rails 4 CMS Engine
gem 'comfortable_mexican_sofa', '1.12.7'	

# A Ruby interface to the Twitter API
gem 'twitter', '5.14.0'

# Ruby SDK for Facebook
gem 'koala', '~> 2.0.0rc1'

# HTML, XML, SAX, and Reader parser 
gem 'nokogiri', '1.6.6.2'

#using new_relic for monitoring the application
gem 'newrelic_rpm'

# spree quickbooks integration
gem 'spree_quickbooks', github: 'chubarovNick/spree_quickbooks'
# gem 'searchkick'

gem 'spree_editor', github: 'spree-contrib/spree_editor', branch: '2-4-stable'
gem 'sidekiq', '~> 3.5', '>= 3.5.1'
gem 'carrierwave'
gem 'mini_magick'
